name: csgoMatchPinger
description: A simple command-line application.
version: 0.1.0
homepage: https://github.com/Ar4ys/csgo_match_pinger

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies: 
  dio: ^3.0.10
  path: ^1.8.0
  stack_trace: ^1.10.0
  watcher: ^1.0.0
  win32: ^2.0.4
dev_dependencies: 
  pedantic: ^1.11.0
